### ISSUE TITLE
Lgandd with discrete parents only

### ISSUE THREAD

**Issue by benavente** [CyberPoint/libpgm#12]
I'm using Lgandd with discrete parents only. The documentation says that such nodes must have one or more discrete parents **and** one or more Lg parents.

As far as I can tell from the source code, it should work correctly exclusively with discrete parents. Is that correct or am I missing something?

The problem is that it works, but I get a warning message each time a sample is drawn:
```Did not find LG and discrete type parents.```

**Comment by Patbenavente** [comment]
I created a pull request for this.

**Comment by raugasm** [comment]
Merged.  Thank you!
