### ISSUE TITLE
Issue with setting the seed for experiment replication

### ISSUE THREAD

**Issue by yegortk** [CyberPoint/libpgm#16]
I believe  ' random.seed() '  should be removed in all of the following files. Its use sets the seed to some random value every time the library is used. Because of this, it is impossible to replicate any results exactly. Instead, user should be able to specify the desired seed before the library is used - and package should not override his choice.

List of files:
libpgm/CPDtypes/discrete.py
libpgm/CPDtypes/lg.py
libpgm/CPDtypes/lgandd.py 
libpgm/hybayesiannetwork.py 
libpgm/lgbayesiannetwork.py 
libpgm/discretebayesiannetwork.py
libpgm/dyndiscbayesiannetwork.py
libpgm/tablecpdfactorization.py

**Comment by mark-raugas** [comment]
I agree, assuming there is an option to get a random seed if desired.  If you make a pull request, I will marge your changes in.
